language: python
python:
    - "3.3"
    - "3.4"
install: pip install -r requirements-test.txt
script: ./run-tests.sh
after_success:
    - coveralls
notifications:
    email:
        - jturk@sunlightfoundation.com
