language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
install: pip install pytest pytest-cov pytest-django coveralls
script: ./run-tests.sh
after_success:
    - coveralls
notifications:
    email:
        - james@openstates.org
